
FROM node:12.6 as node

COPY config/node/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

ENTRYPOINT ["docker-entrypoint"]

FROM node as node_development

WORKDIR /srv/app

HEALTHCHECK --interval=30s --timeout=5s --retries=5 CMD curl --fail http://localhost || exit 1

ENV HOST=0.0.0.0
ENV PORT=80

CMD ["npm", "run", "dev"]

COPY frontend /srv/app/
RUN npm install

FROM node_development as node_production
WORKDIR /srv/app
#clean up
# do not use .env /  test files in production
RUN rm -f .env*

CMD ["npm", "run", "start"]

FROM node as docs
RUN npm install docsify-cli -g

HEALTHCHECK --interval=30s --timeout=5s --retries=5 CMD curl --fail http://localhost:3000 || exit 1

CMD ["docsify", "serve" ,"docs"]

FROM docs as docs_final

