
FROM node:12.6 as node

COPY config/node/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN  set -eux; \
    chmod +x /usr/local/bin/docker-entrypoint ; \
    #We have installed curl?
    curl --version

ENTRYPOINT ["docker-entrypoint"]

FROM node as node_development

WORKDIR /srv/app

HEALTHCHECK --start-period=5m CMD curl --fail http://localhost || exit 1

ENV HOST=0.0.0.0
ENV PORT=80

CMD ["npm", "run", "dev"]

FROM node_development as node_production

WORKDIR /srv/app

COPY frontend /srv/app/
RUN  set -eux; \
    npm install ; \
    npm run build ; \
    #clean up
    rm -f .env*

CMD ["npm", "run", "start"]

FROM node as docs_development

RUN npm install docsify-cli -g

HEALTHCHECK --start-period=5m CMD curl --fail http://localhost:3000 || exit 1

CMD ["docsify", "serve" ,"docs"]

