FROM rabbitmq:3.8-management-alpine as rabbitmq-management

COPY config/rabbitmq/ergonode-docker-entrypoint.sh /usr/local/bin/ergonode-docker-entrypoint.sh
RUN chmod +x /usr/local/bin/ergonode-docker-entrypoint.sh
ENTRYPOINT ["ergonode-docker-entrypoint.sh"]
CMD ["rabbitmq-server"]

FROM rabbitmq:3.8-alpine as rabbitmq

COPY config/rabbitmq/ergonode-docker-entrypoint.sh /usr/local/bin/ergonode-docker-entrypoint.sh
RUN set -eux ; \
    chmod +x /usr/local/bin/ergonode-docker-entrypoint.sh ; \
    rabbitmq-plugins enable --offline rabbitmq_management_agent ; \
    echo "management.tcp.port = 15672" >> /etc/rabbitmq/rabbitmq.conf

ENTRYPOINT ["ergonode-docker-entrypoint.sh"]
CMD ["rabbitmq-server"]
