version: "3.7"

services:

    postgres:
        image: "postgres:10"
        volumes:
            - "./data/.postgres:/var/lib/postgresql/data:delegated"
            - "./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "123"
            POSTGRES_DB: "postgres"
        ports:
            - "5432"

    php:
        build:
            context: "./"
            dockerfile: "./config/php/Dockerfile"
        working_dir: "/srv/app"
        entrypoint: "/entrypoint.sh"
        volumes:
            - "./backend:/srv/app:delegated"
            - "./config/php/cron:/etc/cron.d:delegated"
            - "./config/php/conf.d/php-ini-override.ini:/usr/local/etc/php/conf.d/php-ini-override.ini"
            - "./config/php/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf"
            - "./config/php/supervisor/conf.d:/etc/supervisor/conf.d:delegated"
            - "./config/php/docker-entrypoint.sh:/entrypoint.sh:delegated"
        environment:
            XDEBUG_CONFIG: ${XDEBUG_CONFIG}
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
            APP_URL: "http://nginx"
        links:
            - "postgres"
        depends_on:
            - "postgres"
            - "mailhog"
            - "rabbitmq"

    rabbitmq:
        image: "rabbitmq:3.8"
        environment:
            RABBITMQ_DEFAULT_USER: "ergonode"
            RABBITMQ_DEFAULT_PASS: "ergonode"
        ports:
            - "5672"
            - "15672"

    nginx:
        image: "nginx:1.17"
        volumes:
            - "./backend:/srv/app:delegated"
            - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./config/nginx/conf.d:/etc/nginx/conf.d:delegated"
        working_dir: "/srv/app"
        ports:
            - "8000:80"
        depends_on:
            - "php"
            - "nuxtjs"

    mailhog:
        image: "mailhog/mailhog"
        ports:
            - "1025"
            - "8025"

    nuxtjs:
        image: "gerardojunior/nuxtjs:stable"
        working_dir: "/src"
        command: "dev"
        volumes:
            - "./frontend:/src:delegated"
        ports:
            - "80"
        environment:
            API_BASE_URL: "http://localhost:8000/api/v1/"

networks:
    default:
