
FROM postgres:10-alpine as postgres_development

COPY ./config/postgres/docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
ADD ./config/postgres/postgres-healthcheck.sh  /usr/local/bin/postgres-healthcheck.sh
RUN chmod +x /usr/local/bin/postgres-healthcheck.sh

HEALTHCHECK --start-period=5s CMD bash -c /usr/local/bin/postgres-healthcheck.sh

FROM postgres_development as postgres_production
